python2.7 '/home/vasily/git/scripts_open/scripts_open/gwy_convert.py'
cd processed_data
cd line_int
python '/home/vasily/git/scripts_open/scripts_open/plot_lines.py'
cd ..
cd fft_diff
python '/home/vasily/git/scripts_open/scripts_open/plot_ED_XRD.py'
cd ..
cd ..
python '/home/vasily/git/scripts_open/scripts_open/combine.py'
